---
output: github_document
---

# FMT

Purpose of this project is to provide analytics for Forward MT and Forward MT Foundation's social media and communications data. The following are the main questions addressed;

* When is the best time day of week and time of day to post/send emails?
* Do graphics or photos have higher engagement rates?
* How does frequency of emails influence open rates?

Below are specific questions by communications strategy. Perform analysis for FMT and FMTF independently.

**Email**

* What day of the week and time of day have the highest open rates, when accounting for recipients?
* What combination of day and time had highest open rates, when accounting for recipients?
* How does frequency of emails in a week influence open rate?


**Instagram**

* What day of the week and time of day have the highest engagement?
* What combination of day and time had highest engagement?
* Do graphics or photos have higher engagement rates?


**Facebook**

* What day of the week and time of day have the highest engagement?
* What combination of day and time had highest engagement?
* Do graphics or photos have higher engagement rates?


**TikTok**

* What day of the week and time of day have the highest engagement?
* What combination of day and time had highest engagement?


